create table usuario (
 id int(11) not null auto_increment,
 nombre varchar(100) not null,
 clave varchar(45) not null,
 fecha_creacion datetime null,
 primary key (id)
);
create table servicio (
 id int(11) not null auto_increment,
 id_usuario int(11) not null,
 tipo_usuario int(11) not null,
 tipo_servicio int(11) not null,
 id_mascota int(11) not null,
 fecha_programada datetime null,
 fecha_entrega datetime null,
 fecha_contable datetime null,
 total double(20) not null,
 primary key (id)
);
create table mascota (
 id int(11) not null auto_increment,
 nombre varchar(100) not null,
 especie varchar(100) not null,
 raza varchar(100) not null,
 id_cliente int(11) not null,
 primary key (id)
);
create table cliente (
 id int(11) not null auto_increment,
 identificacion bigint not null,
 nombre varchar(100) not null,
 direccion varchar(100) not null,
 telefono bigint not null,
 primary key (id)
);
create table tipo_cliente (
	id int(11) not null auto_increment,
	descripcion VARCHAR(8)
);
create table tipo_servicio (
	id int(11) not null auto_increment,
	descripcion VARCHAR(11),
	costo double(20) not null
);

insert into cliente (identificacion, nombre, direccion, telefono) values (88565419, 'Marrilee Winridge', '9753 Mesta Hill', 6087895);
insert into cliente (identificacion, nombre, direccion, telefono) values (1740590, 'Udell Wicher', '80002 Washington Pass', 5740198);
insert into cliente (identificacion, nombre, direccion, telefono) values (68697428, 'Arman Piletic', '0 Meadow Vale Crossing', 8524714);
insert into cliente (identificacion, nombre, direccion, telefono) values (71667918, 'Wallache Sille', '443 Meadow Ridge Way', 8583121);
insert into cliente (identificacion, nombre, direccion, telefono) values (70684877, 'Dallis Christiensen', '802 Merrick Parkway', 4227374);
insert into cliente (identificacion, nombre, direccion, telefono) values (43268085, 'Freida Simkovich', '39 Claremont Court', 6404059);
insert into cliente (identificacion, nombre, direccion, telefono) values (66324616, 'Brody Gabbatiss', '5054 Namekagon Terrace', 3938082);
insert into cliente (identificacion, nombre, direccion, telefono) values (23022311, 'Trstram Kemmons', '0 Fisk Point', 7860783);
insert into cliente (identificacion, nombre, direccion, telefono) values (64402555, 'Eliza Pendreigh', '5353 South Street', 5543425);
insert into cliente (identificacion, nombre, direccion, telefono) values (46944632, 'Robinia Antoniak', '8 Bluejay Park', 5554663);
insert into cliente (identificacion, nombre, direccion, telefono) values (71432585, 'Gallagher Syplus', '294 Arrowood Lane', 6584124);
insert into cliente (identificacion, nombre, direccion, telefono) values (32863073, 'Hashim Petronis', '2961 Morrow Place', 4211623);
insert into cliente (identificacion, nombre, direccion, telefono) values (94644129, 'Shaylah Ladd', '2655 Clemons Lane', 4014724);
insert into cliente (identificacion, nombre, direccion, telefono) values (67518715, 'Elsi Heijnen', '36 Arkansas Park', 4766242);
insert into cliente (identificacion, nombre, direccion, telefono) values (41042595, 'Teodoor Denham', '9 Buena Vista Avenue', 8075893);
insert into cliente (identificacion, nombre, direccion, telefono) values (73527248, 'Douglas Douch', '1239 American Circle', 3949577);
insert into cliente (identificacion, nombre, direccion, telefono) values (29488889, 'Sherman Petrashov', '40 Pennsylvania Drive', 3776599);
insert into cliente (identificacion, nombre, direccion, telefono) values (98011707, 'Danit Muckle', '5777 Beilfuss Court', 5331833);
insert into cliente (identificacion, nombre, direccion, telefono) values (78879752, 'Lem Pickerell', '55728 Spenser Avenue', 6698117);
insert into cliente (identificacion, nombre, direccion, telefono) values (73455843, 'Johnathan Greenhall', '740 Stuart Place', 5005600);
insert into cliente (identificacion, nombre, direccion, telefono) values (91704094, 'Milka Hauxwell', '02433 Scott Drive', 7267095);
insert into cliente (identificacion, nombre, direccion, telefono) values (17079922, 'Cecelia Darrow', '87990 Holmberg Alley', 3975968);
insert into cliente (identificacion, nombre, direccion, telefono) values (33267334, 'Glenine Dunan', '791 Green Ridge Trail', 6737071);
insert into cliente (identificacion, nombre, direccion, telefono) values (74343649, 'Billie Double', '4895 Washington Circle', 6172581);
insert into cliente (identificacion, nombre, direccion, telefono) values (81048984, 'Pepi Shillan', '83 Starling Plaza', 4559585);
insert into cliente (identificacion, nombre, direccion, telefono) values (89432629, 'Justine Mackriell', '3861 Blackbird Circle', 8689471);
insert into cliente (identificacion, nombre, direccion, telefono) values (98407248, 'Zora Chetwind', '38788 Forest Dale Plaza', 3280039);
insert into cliente (identificacion, nombre, direccion, telefono) values (48028746, 'Berna Grierson', '8 Lien Road', 4560660);
insert into cliente (identificacion, nombre, direccion, telefono) values (91424448, 'Finlay Josefson', '96 Portage Avenue', 6317675);
insert into cliente (identificacion, nombre, direccion, telefono) values (27739982, 'Moselle Curwood', '06 Clemons Terrace', 4861976);
insert into cliente (identificacion, nombre, direccion, telefono) values (11948612, 'Josh Rodear', '3 Rigney Alley', 5022441);
insert into cliente (identificacion, nombre, direccion, telefono) values (52829675, 'Pegeen Mawdsley', '93 Hanson Alley', 4885016);
insert into cliente (identificacion, nombre, direccion, telefono) values (38424188, 'Yorker Goggins', '98626 Talisman Plaza', 5673745);
insert into cliente (identificacion, nombre, direccion, telefono) values (36116708, 'Quinn Starrs', '721 Corben Hill', 8505153);
insert into cliente (identificacion, nombre, direccion, telefono) values (56918062, 'Margo Turnock', '63283 Muir Place', 8403016);
insert into cliente (identificacion, nombre, direccion, telefono) values (90687379, 'Heidie Lingard', '0 Magdeline Road', 3664164);
insert into cliente (identificacion, nombre, direccion, telefono) values (19956222, 'Adoree Erdely', '565 North Terrace', 3159759);
insert into cliente (identificacion, nombre, direccion, telefono) values (75804771, 'Fraser Simnell', '4 Sherman Way', 3951535);
insert into cliente (identificacion, nombre, direccion, telefono) values (19108691, 'Von Nasi', '97457 Arapahoe Place', 5378462);
insert into cliente (identificacion, nombre, direccion, telefono) values (62333771, 'Wilie Trevena', '7182 Montana Lane', 7051483);
insert into cliente (identificacion, nombre, direccion, telefono) values (68085541, 'Laura Germain', '840 Morningstar Circle', 5477547);
insert into cliente (identificacion, nombre, direccion, telefono) values (93760380, 'Findlay Barrat', '865 Gateway Road', 6154078);
insert into cliente (identificacion, nombre, direccion, telefono) values (21533632, 'Lenore Wolters', '16 Texas Avenue', 6471767);
insert into cliente (identificacion, nombre, direccion, telefono) values (63119318, 'Tome Alywen', '417 Kropf Street', 8559734);
insert into cliente (identificacion, nombre, direccion, telefono) values (76928415, 'Obidiah Taylour', '367 Bartelt Hill', 4998950);
insert into cliente (identificacion, nombre, direccion, telefono) values (33313572, 'Lina Boyall', '675 Fairview Center', 6565110);
insert into cliente (identificacion, nombre, direccion, telefono) values (38849091, 'Diannne Kuhnel', '9256 Fair Oaks Alley', 8748046);
insert into cliente (identificacion, nombre, direccion, telefono) values (79753192, 'Gabriela Sheed', '2 Brown Park', 6597708);
insert into cliente (identificacion, nombre, direccion, telefono) values (6414469, 'Valery Whittaker', '283 Green Trail', 5339615);
insert into cliente (identificacion, nombre, direccion, telefono) values (94039899, 'Georgette Point', '4811 Springs Parkway', 6844740);
insert into cliente (identificacion, nombre, direccion, telefono) values (6862417, 'Viv Paulino', '65818 Thierer Road', 6385792);
insert into cliente (identificacion, nombre, direccion, telefono) values (14312791, 'Nathanael Stillert', '0 Dunning Junction', 5508631);
insert into cliente (identificacion, nombre, direccion, telefono) values (40540844, 'Ike MacCulloch', '32 Randy Hill', 7216405);
insert into cliente (identificacion, nombre, direccion, telefono) values (56141472, 'Hunfredo Choat', '94188 Towne Parkway', 3421051);
insert into cliente (identificacion, nombre, direccion, telefono) values (3200664, 'Juliana McMeeking', '4 Westend Road', 3150443);
insert into cliente (identificacion, nombre, direccion, telefono) values (12775525, 'Jacenta Stockings', '91 Village Green Alley', 5958327);
insert into cliente (identificacion, nombre, direccion, telefono) values (67476399, 'Rockey Gorringe', '21 Goodland Alley', 4951055);
insert into cliente (identificacion, nombre, direccion, telefono) values (7979417, 'Granville Jillard', '192 Towne Place', 3721949);
insert into cliente (identificacion, nombre, direccion, telefono) values (18230664, 'Anet McCarrick', '216 Grasskamp Place', 8210346);
insert into cliente (identificacion, nombre, direccion, telefono) values (47667671, 'Esmaria Lillie', '7 Oriole Avenue', 3335858);
insert into cliente (identificacion, nombre, direccion, telefono) values (94132262, 'Hoyt Arbor', '5646 Pennsylvania Crossing', 7440169);
insert into cliente (identificacion, nombre, direccion, telefono) values (44670684, 'Chrisy Tibbits', '7 Harbort Pass', 4485404);
insert into cliente (identificacion, nombre, direccion, telefono) values (23010810, 'Brice Diggles', '79382 Hallows Park', 7567715);
insert into cliente (identificacion, nombre, direccion, telefono) values (20479363, 'Yuma Tatem', '6 Hermina Junction', 8646751);
insert into cliente (identificacion, nombre, direccion, telefono) values (22184020, 'Mathias Alchin', '96685 American Pass', 8143583);
insert into cliente (identificacion, nombre, direccion, telefono) values (98032267, 'Barbara Mephan', '212 Dayton Avenue', 5486767);
insert into cliente (identificacion, nombre, direccion, telefono) values (97645895, 'Judith Martynov', '3 Butterfield Street', 7854923);
insert into cliente (identificacion, nombre, direccion, telefono) values (33673117, 'Zorine Tanfield', '3 Blackbird Circle', 6391425);
insert into cliente (identificacion, nombre, direccion, telefono) values (62914574, 'Flossy Cough', '49 David Junction', 8346472);
insert into cliente (identificacion, nombre, direccion, telefono) values (2998927, 'Baldwin Pear', '0 Morrow Road', 4519952);
insert into cliente (identificacion, nombre, direccion, telefono) values (79162054, 'Demetra Arlow', '82522 Susan Park', 7650664);
insert into cliente (identificacion, nombre, direccion, telefono) values (72100945, 'Vivien Brightey', '37932 Garrison Parkway', 5520661);
insert into cliente (identificacion, nombre, direccion, telefono) values (61648058, 'Denis Teideman', '0 Summit Drive', 3511262);
insert into cliente (identificacion, nombre, direccion, telefono) values (81090747, 'Burty Enstone', '2971 Carioca Crossing', 7070985);
insert into cliente (identificacion, nombre, direccion, telefono) values (7284632, 'Brockie Baumann', '410 Holy Cross Crossing', 3145526);
insert into cliente (identificacion, nombre, direccion, telefono) values (16641807, 'Timmie Crocetti', '8 Pearson Street', 3057912);
insert into cliente (identificacion, nombre, direccion, telefono) values (20399311, 'Alford Mussett', '46863 Westridge Park', 7183808);
insert into cliente (identificacion, nombre, direccion, telefono) values (66959956, 'Frants Roderigo', '737 Comanche Alley', 6340437);
insert into cliente (identificacion, nombre, direccion, telefono) values (34407740, 'Catharina Arch', '382 Orin Point', 3071829);
insert into cliente (identificacion, nombre, direccion, telefono) values (23598068, 'Lorrin Taylor', '5343 Corry Place', 4946480);
insert into cliente (identificacion, nombre, direccion, telefono) values (12211786, 'Welsh Physick', '9754 Hollow Ridge Center', 5123374);
insert into cliente (identificacion, nombre, direccion, telefono) values (35107010, 'Cahra Cottle', '437 Everett Court', 3570886);
insert into cliente (identificacion, nombre, direccion, telefono) values (23404390, 'Billie Colicot', '64 Schmedeman Trail', 6094672);
insert into cliente (identificacion, nombre, direccion, telefono) values (47779807, 'Honey Teodori', '78803 Arkansas Hill', 4924028);
insert into cliente (identificacion, nombre, direccion, telefono) values (74865962, 'Sofia Wasylkiewicz', '75221 Eastlawn Avenue', 3172942);
insert into cliente (identificacion, nombre, direccion, telefono) values (74063265, 'Rafaello Smalley', '27668 Merry Street', 8996878);
insert into cliente (identificacion, nombre, direccion, telefono) values (8979660, 'Clevie Okroy', '1 Nobel Crossing', 4855820);
insert into cliente (identificacion, nombre, direccion, telefono) values (26447531, 'Aubrie Pinard', '204 Vermont Place', 3858989);
insert into cliente (identificacion, nombre, direccion, telefono) values (72179277, 'Lindsay Borborough', '0 Carey Lane', 8710315);
insert into cliente (identificacion, nombre, direccion, telefono) values (96571174, 'Sofie McBeath', '76 Knutson Lane', 6827055);
insert into cliente (identificacion, nombre, direccion, telefono) values (41080022, 'Xenos Imloch', '250 Grasskamp Junction', 8850725);
insert into cliente (identificacion, nombre, direccion, telefono) values (82182300, 'Brenna Mander', '88375 Forest Dale Junction', 5883840);
insert into cliente (identificacion, nombre, direccion, telefono) values (41540842, 'Marvin Auletta', '84565 Lillian Court', 6340670);
insert into cliente (identificacion, nombre, direccion, telefono) values (94868799, 'Nissie Frewer', '991 Troy Plaza', 5893394);
insert into cliente (identificacion, nombre, direccion, telefono) values (9622876, 'Bobette Oleksiak', '5399 Dryden Center', 7177689);
insert into cliente (identificacion, nombre, direccion, telefono) values (76209239, 'Clem Sadd', '58 Nancy Pass', 6828333);
insert into cliente (identificacion, nombre, direccion, telefono) values (92667613, 'Esmaria Tatterton', '1 Golf Point', 3543934);
insert into cliente (identificacion, nombre, direccion, telefono) values (65229921, 'Benson Cowdroy', '3808 Heffernan Avenue', 7721029);
insert into cliente (identificacion, nombre, direccion, telefono) values (19310359, 'Feliza Bourtoumieux', '59592 Lyons Hill', 3073767);
insert into cliente (identificacion, nombre, direccion, telefono) values (101152431, 'Terri Marriage', '6680 School Court', 3758094);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nevil', 'German Shepherd', 'PERRO', 36);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bernelle', 'Rottweiler', 'PERRO', 61);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nerta', 'Rottweiler', 'PERRO', 34);
insert into mascota (nombre, raza, especie, id_cliente) values ('Heinrick', 'German Shepherd', 'PERRO', 7);
insert into mascota (nombre, raza, especie, id_cliente) values ('Erich', 'Schnauzer', 'PERRO', 35);
insert into mascota (nombre, raza, especie, id_cliente) values ('Andriette', 'Pitbull', 'PERRO', 68);
insert into mascota (nombre, raza, especie, id_cliente) values ('Antony', 'Schnauzer', 'PERRO', 3);
insert into mascota (nombre, raza, especie, id_cliente) values ('Rhetta', 'Labrador', 'PERRO', 14);
insert into mascota (nombre, raza, especie, id_cliente) values ('Granny', 'Schnauzer', 'PERRO', 40);
insert into mascota (nombre, raza, especie, id_cliente) values ('Kippar', 'Poodle', 'PERRO', 75);
insert into mascota (nombre, raza, especie, id_cliente) values ('Hattie', 'Labrador', 'PERRO', 17);
insert into mascota (nombre, raza, especie, id_cliente) values ('Mauricio', 'German Shepherd', 'PERRO', 51);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tiff', 'Bulldog', 'PERRO', 81);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dasha', 'Schnauzer', 'PERRO', 20);
insert into mascota (nombre, raza, especie, id_cliente) values ('Reinold', 'Poodle', 'PERRO', 85);
insert into mascota (nombre, raza, especie, id_cliente) values ('Worden', 'Poodle', 'PERRO', 100);
insert into mascota (nombre, raza, especie, id_cliente) values ('Pietrek', 'Criollo', 'PERRO', 86);
insert into mascota (nombre, raza, especie, id_cliente) values ('Wilone', 'Labrador', 'PERRO', 95);
insert into mascota (nombre, raza, especie, id_cliente) values ('Leanor', 'Labrador', 'PERRO', 89);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tamma', 'German Shepherd', 'PERRO', 32);
insert into mascota (nombre, raza, especie, id_cliente) values ('Osmond', 'Labrador', 'PERRO', 86);
insert into mascota (nombre, raza, especie, id_cliente) values ('Peyter', 'Pitbull', 'PERRO', 79);
insert into mascota (nombre, raza, especie, id_cliente) values ('Berkie', 'Poodle', 'PERRO', 31);
insert into mascota (nombre, raza, especie, id_cliente) values ('Edlin', 'Pitbull', 'PERRO', 76);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lida', 'Labrador', 'PERRO', 83);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nara', 'Rottweiler', 'PERRO', 78);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sherwood', 'German Shepherd', 'PERRO', 5);
insert into mascota (nombre, raza, especie, id_cliente) values ('Melloney', 'Criollo', 'PERRO', 73);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jone', 'Criollo', 'PERRO', 29);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bran', 'Golden retriever', 'PERRO', 66);
insert into mascota (nombre, raza, especie, id_cliente) values ('Rozanne', 'Poodle', 'PERRO', 6);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ives', 'Bulldog', 'PERRO', 38);
insert into mascota (nombre, raza, especie, id_cliente) values ('Mikey', 'Bulldog', 'PERRO', 93);
insert into mascota (nombre, raza, especie, id_cliente) values ('Orren', 'Poodle', 'PERRO', 13);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bevvy', 'Golden retriever', 'PERRO', 2);
insert into mascota (nombre, raza, especie, id_cliente) values ('Monika', 'German Shepherd', 'PERRO', 27);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ernie', 'Bulldog', 'PERRO', 11);
insert into mascota (nombre, raza, especie, id_cliente) values ('Andrea', 'Rottweiler', 'PERRO', 66);
insert into mascota (nombre, raza, especie, id_cliente) values ('Eward', 'Bulldog', 'PERRO', 10);
insert into mascota (nombre, raza, especie, id_cliente) values ('Maudie', 'Pitbull', 'PERRO', 89);
insert into mascota (nombre, raza, especie, id_cliente) values ('Adam', 'Criollo', 'PERRO', 87);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nerissa', 'Schnauzer', 'PERRO', 86);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sheryl', 'Bulldog', 'PERRO', 62);
insert into mascota (nombre, raza, especie, id_cliente) values ('Carolyne', 'Criollo', 'PERRO', 77);
insert into mascota (nombre, raza, especie, id_cliente) values ('Benedikta', 'Pitbull', 'PERRO', 17);
insert into mascota (nombre, raza, especie, id_cliente) values ('Eula', 'Schnauzer', 'PERRO', 62);
insert into mascota (nombre, raza, especie, id_cliente) values ('Francisca', 'Schnauzer', 'PERRO', 95);
insert into mascota (nombre, raza, especie, id_cliente) values ('Michelle', 'Golden retriever', 'PERRO', 98);
insert into mascota (nombre, raza, especie, id_cliente) values ('Birgit', 'Golden retriever', 'PERRO', 1);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gilberte', 'German Shepherd', 'PERRO', 29);
insert into mascota (nombre, raza, especie, id_cliente) values ('Elnar', 'German Shepherd', 'PERRO', 42);
insert into mascota (nombre, raza, especie, id_cliente) values ('Feodora', 'Pitbull', 'PERRO', 81);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tyler', 'Labrador', 'PERRO', 50);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ilyse', 'Bulldog', 'PERRO', 60);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ewen', 'Golden retriever', 'PERRO', 16);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jessy', 'German Shepherd', 'PERRO', 32);
insert into mascota (nombre, raza, especie, id_cliente) values ('Luce', 'Bulldog', 'PERRO', 53);
insert into mascota (nombre, raza, especie, id_cliente) values ('Yorgos', 'Schnauzer', 'PERRO', 50);
insert into mascota (nombre, raza, especie, id_cliente) values ('Derek', 'Rottweiler', 'PERRO', 31);
insert into mascota (nombre, raza, especie, id_cliente) values ('Judy', 'Golden retriever', 'PERRO', 47);
insert into mascota (nombre, raza, especie, id_cliente) values ('Angie', 'Labrador', 'PERRO', 12);
insert into mascota (nombre, raza, especie, id_cliente) values ('Elenore', 'German Shepherd', 'PERRO', 55);
insert into mascota (nombre, raza, especie, id_cliente) values ('Mahmud', 'Poodle', 'PERRO', 26);
insert into mascota (nombre, raza, especie, id_cliente) values ('Natty', 'German Shepherd', 'PERRO', 83);
insert into mascota (nombre, raza, especie, id_cliente) values ('Matthiew', 'Schnauzer', 'PERRO', 33);
insert into mascota (nombre, raza, especie, id_cliente) values ('Avie', 'German Shepherd', 'PERRO', 65);
insert into mascota (nombre, raza, especie, id_cliente) values ('Horatio', 'Criollo', 'PERRO', 3);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ezri', 'German Shepherd', 'PERRO', 63);
insert into mascota (nombre, raza, especie, id_cliente) values ('Maurice', 'Bulldog', 'PERRO', 41);
insert into mascota (nombre, raza, especie, id_cliente) values ('Trude', 'Criollo', 'PERRO', 14);
insert into mascota (nombre, raza, especie, id_cliente) values ('Antonin', 'Criollo', 'PERRO', 3);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dianna', 'Rottweiler', 'PERRO', 86);
insert into mascota (nombre, raza, especie, id_cliente) values ('Letitia', 'Bulldog', 'PERRO', 60);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sheeree', 'Schnauzer', 'PERRO', 98);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lelia', 'Rottweiler', 'PERRO', 62);
insert into mascota (nombre, raza, especie, id_cliente) values ('Arty', 'Labrador', 'PERRO', 36);
insert into mascota (nombre, raza, especie, id_cliente) values ('Shay', 'Pitbull', 'PERRO', 95);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tildie', 'Pitbull', 'PERRO', 59);
insert into mascota (nombre, raza, especie, id_cliente) values ('Haley', 'Labrador', 'PERRO', 32);
insert into mascota (nombre, raza, especie, id_cliente) values ('Naoma', 'Golden retriever', 'PERRO', 87);
insert into mascota (nombre, raza, especie, id_cliente) values ('Joni', 'Golden retriever', 'PERRO', 76);
insert into mascota (nombre, raza, especie, id_cliente) values ('Babbette', 'Poodle', 'PERRO', 37);
insert into mascota (nombre, raza, especie, id_cliente) values ('Pearle', 'Pitbull', 'PERRO', 13);
insert into mascota (nombre, raza, especie, id_cliente) values ('Freddy', 'Criollo', 'PERRO', 27);
insert into mascota (nombre, raza, especie, id_cliente) values ('Geoffry', 'Criollo', 'PERRO', 70);
insert into mascota (nombre, raza, especie, id_cliente) values ('Malynda', 'Schnauzer', 'PERRO', 64);
insert into mascota (nombre, raza, especie, id_cliente) values ('Way', 'Golden retriever', 'PERRO', 75);
insert into mascota (nombre, raza, especie, id_cliente) values ('Marika', 'Criollo', 'PERRO', 10);
insert into mascota (nombre, raza, especie, id_cliente) values ('Erwin', 'Poodle', 'PERRO', 47);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lela', 'Pitbull', 'PERRO', 31);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sloan', 'Golden retriever', 'PERRO', 1);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lynna', 'German Shepherd', 'PERRO', 76);
insert into mascota (nombre, raza, especie, id_cliente) values ('Hakim', 'Rottweiler', 'PERRO', 29);
insert into mascota (nombre, raza, especie, id_cliente) values ('Moise', 'Rottweiler', 'PERRO', 56);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nissy', 'Poodle', 'PERRO', 98);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gusty', 'Poodle', 'PERRO', 12);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nydia', 'Schnauzer', 'PERRO', 6);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tirrell', 'Criollo', 'PERRO', 35);
insert into mascota (nombre, raza, especie, id_cliente) values ('Kailey', 'Golden retriever', 'PERRO', 40);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lewie', 'German Shepherd', 'PERRO', 9);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ode', 'German Shepherd', 'PERRO', 45);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jillane', 'German Shepherd', 'PERRO', 97);
insert into mascota (nombre, raza, especie, id_cliente) values ('Winslow', 'Golden retriever', 'PERRO', 26);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sydelle', 'Criollo', 'PERRO', 37);
insert into mascota (nombre, raza, especie, id_cliente) values ('Keri', 'Rottweiler', 'PERRO', 16);
insert into mascota (nombre, raza, especie, id_cliente) values ('Neale', 'Criollo', 'PERRO', 16);
insert into mascota (nombre, raza, especie, id_cliente) values ('Kane', 'German Shepherd', 'PERRO', 46);
insert into mascota (nombre, raza, especie, id_cliente) values ('Stacie', 'German Shepherd', 'PERRO', 55);
insert into mascota (nombre, raza, especie, id_cliente) values ('Errick', 'Bulldog', 'PERRO', 33);
insert into mascota (nombre, raza, especie, id_cliente) values ('Irita', 'Poodle', 'PERRO', 82);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dian', 'Poodle', 'PERRO', 56);
insert into mascota (nombre, raza, especie, id_cliente) values ('Melisent', 'Golden retriever', 'PERRO', 75);
insert into mascota (nombre, raza, especie, id_cliente) values ('Corie', 'Poodle', 'PERRO', 21);
insert into mascota (nombre, raza, especie, id_cliente) values ('Aloysia', 'Poodle', 'PERRO', 32);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gina', 'Schnauzer', 'PERRO', 64);
insert into mascota (nombre, raza, especie, id_cliente) values ('Meggie', 'Pitbull', 'PERRO', 89);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bettine', 'Pitbull', 'PERRO', 26);
insert into mascota (nombre, raza, especie, id_cliente) values ('Felipa', 'Schnauzer', 'PERRO', 41);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lutero', 'Criollo', 'PERRO', 77);
insert into mascota (nombre, raza, especie, id_cliente) values ('Steven', 'German Shepherd', 'PERRO', 38);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sloan', 'German Shepherd', 'PERRO', 48);
insert into mascota (nombre, raza, especie, id_cliente) values ('Risa', 'Poodle', 'PERRO', 98);
insert into mascota (nombre, raza, especie, id_cliente) values ('Hester', 'Rottweiler', 'PERRO', 67);
insert into mascota (nombre, raza, especie, id_cliente) values ('Madison', 'German Shepherd', 'PERRO', 14);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tripp', 'Pitbull', 'PERRO', 10);
insert into mascota (nombre, raza, especie, id_cliente) values ('Edan', 'Schnauzer', 'PERRO', 23);
insert into mascota (nombre, raza, especie, id_cliente) values ('Averell', 'Labrador', 'PERRO', 40);
insert into mascota (nombre, raza, especie, id_cliente) values ('Julianne', 'Criollo', 'PERRO', 19);
insert into mascota (nombre, raza, especie, id_cliente) values ('Broddie', 'Rottweiler', 'PERRO', 59);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nathaniel', 'Criollo', 'PERRO', 76);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bancroft', 'Bulldog', 'PERRO', 100);
insert into mascota (nombre, raza, especie, id_cliente) values ('Farica', 'Schnauzer', 'PERRO', 70);
insert into mascota (nombre, raza, especie, id_cliente) values ('Vanya', 'Labrador', 'PERRO', 83);
insert into mascota (nombre, raza, especie, id_cliente) values ('Eddi', 'Golden retriever', 'PERRO', 42);
insert into mascota (nombre, raza, especie, id_cliente) values ('Rozanna', 'Rottweiler', 'PERRO', 41);
insert into mascota (nombre, raza, especie, id_cliente) values ('Arlena', 'Rottweiler', 'PERRO', 5);
insert into mascota (nombre, raza, especie, id_cliente) values ('Peggi', 'Bulldog', 'PERRO', 7);
insert into mascota (nombre, raza, especie, id_cliente) values ('Guinevere', 'Golden retriever', 'PERRO', 33);
insert into mascota (nombre, raza, especie, id_cliente) values ('Douglass', 'Criollo', 'PERRO', 73);
insert into mascota (nombre, raza, especie, id_cliente) values ('Franklin', 'German Shepherd', 'PERRO', 50);
insert into mascota (nombre, raza, especie, id_cliente) values ('Debi', 'Labrador', 'PERRO', 92);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jayne', 'Pitbull', 'PERRO', 24);
insert into mascota (nombre, raza, especie, id_cliente) values ('Maureene', 'Poodle', 'PERRO', 28);
insert into mascota (nombre, raza, especie, id_cliente) values ('Alfy', 'Pitbull', 'PERRO', 27);
insert into mascota (nombre, raza, especie, id_cliente) values ('Charlean', 'Rottweiler', 'PERRO', 39);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gertrudis', 'Schnauzer', 'PERRO', 15);
insert into mascota (nombre, raza, especie, id_cliente) values ('Vance', 'Bulldog', 'PERRO', 44);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dode', 'Criollo', 'PERRO', 91);
insert into mascota (nombre, raza, especie, id_cliente) values ('Othelia', 'Pitbull', 'PERRO', 32);
insert into mascota (nombre, raza, especie, id_cliente) values ('Margalit', 'German Shepherd', 'PERRO', 2);
insert into mascota (nombre, raza, especie, id_cliente) values ('Shantee', 'Schnauzer', 'PERRO', 83);
insert into mascota (nombre, raza, especie, id_cliente) values ('Con', 'Poodle', 'PERRO', 4);
insert into mascota (nombre, raza, especie, id_cliente) values ('Aretha', 'German Shepherd', 'PERRO', 86);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dennie', 'Golden retriever', 'PERRO', 8);
insert into mascota (nombre, raza, especie, id_cliente) values ('Terry', 'Pitbull', 'PERRO', 54);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nickolai', 'Bulldog', 'PERRO', 35);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lyndsie', 'German Shepherd', 'PERRO', 12);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jena', 'Schnauzer', 'PERRO', 20);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ermanno', 'Labrador', 'PERRO', 77);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gayler', 'Criollo', 'PERRO', 85);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nathanil', 'Rottweiler', 'PERRO', 27);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bail', 'Criollo', 'PERRO', 33);
insert into mascota (nombre, raza, especie, id_cliente) values ('Rainer', 'Labrador', 'PERRO', 25);
insert into mascota (nombre, raza, especie, id_cliente) values ('Vanya', 'Criollo', 'PERRO', 95);
insert into mascota (nombre, raza, especie, id_cliente) values ('Deni', 'Poodle', 'PERRO', 33);
insert into mascota (nombre, raza, especie, id_cliente) values ('Celie', 'Criollo', 'PERRO', 17);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ive', 'Rottweiler', 'PERRO', 97);
insert into mascota (nombre, raza, especie, id_cliente) values ('Worth', 'Schnauzer', 'PERRO', 5);
insert into mascota (nombre, raza, especie, id_cliente) values ('Emyle', 'Rottweiler', 'PERRO', 75);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ferris', 'Poodle', 'PERRO', 26);
insert into mascota (nombre, raza, especie, id_cliente) values ('Corney', 'Poodle', 'PERRO', 51);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lodovico', 'Bulldog', 'PERRO', 75);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jervis', 'Golden retriever', 'PERRO', 4);
insert into mascota (nombre, raza, especie, id_cliente) values ('Laurie', 'Bulldog', 'PERRO', 29);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gilly', 'Labrador', 'PERRO', 2);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nev', 'Rottweiler', 'PERRO', 56);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sylas', 'Golden retriever', 'PERRO', 82);
insert into mascota (nombre, raza, especie, id_cliente) values ('Susy', 'Schnauzer', 'PERRO', 43);
insert into mascota (nombre, raza, especie, id_cliente) values ('Joell', 'Labrador', 'PERRO', 85);
insert into mascota (nombre, raza, especie, id_cliente) values ('Markus', 'Labrador', 'PERRO', 11);
insert into mascota (nombre, raza, especie, id_cliente) values ('Vladimir', 'Poodle', 'PERRO', 66);
insert into mascota (nombre, raza, especie, id_cliente) values ('Chauncey', 'Labrador', 'PERRO', 68);
insert into mascota (nombre, raza, especie, id_cliente) values ('Darby', 'Criollo', 'PERRO', 81);
insert into mascota (nombre, raza, especie, id_cliente) values ('Valle', 'Poodle', 'PERRO', 13);
insert into mascota (nombre, raza, especie, id_cliente) values ('El', 'German Shepherd', 'PERRO', 11);
insert into mascota (nombre, raza, especie, id_cliente) values ('Alanna', 'Bulldog', 'PERRO', 39);
insert into mascota (nombre, raza, especie, id_cliente) values ('Livvie', 'Rottweiler', 'PERRO', 76);
insert into mascota (nombre, raza, especie, id_cliente) values ('Brocky', 'Labrador', 'PERRO', 69);
insert into mascota (nombre, raza, especie, id_cliente) values ('Roseanne', 'Labrador', 'PERRO', 18);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bernardine', 'Pitbull', 'PERRO', 19);
insert into mascota (nombre, raza, especie, id_cliente) values ('Zulema', 'German Shepherd', 'PERRO', 70);
insert into mascota (nombre, raza, especie, id_cliente) values ('Iggy', 'Golden retriever', 'PERRO', 18);
insert into mascota (nombre, raza, especie, id_cliente) values ('Alison', 'Schnauzer', 'PERRO', 88);
insert into mascota (nombre, raza, especie, id_cliente) values ('Holden', 'Rottweiler', 'PERRO', 100);
insert into mascota (nombre, raza, especie, id_cliente) values ('Shanon', 'Poodle', 'PERRO', 41);
insert into mascota (nombre, raza, especie, id_cliente) values ('Booth', 'Labrador', 'PERRO', 69);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jeno', 'German Shepherd', 'PERRO', 69);
insert into mascota (nombre, raza, especie, id_cliente) values ('Den', 'German Shepherd', 'PERRO', 25);
insert into mascota (nombre, raza, especie, id_cliente) values ('Artemas', 'Labrador', 'PERRO', 9);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ruprecht', 'Poodle', 'PERRO', 85);
insert into mascota (nombre, raza, especie, id_cliente) values ('Moyna', 'Abisinio', 'GATO', 68);
insert into mascota (nombre, raza, especie, id_cliente) values ('Rudy', 'Abisinio', 'GATO', 17);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jamima', 'Bengala', 'GATO', 87);
insert into mascota (nombre, raza, especie, id_cliente) values ('Teresita', 'Bengala', 'GATO', 94);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gray', 'Abisinio', 'GATO', 3);
insert into mascota (nombre, raza, especie, id_cliente) values ('Minor', 'Angora', 'GATO', 59);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jehanna', 'siames', 'GATO', 56);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tobiah', 'esfinge', 'GATO', 35);
insert into mascota (nombre, raza, especie, id_cliente) values ('Carlyle', 'Angora', 'GATO', 9);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gerladina', 'Angora', 'GATO', 51);
insert into mascota (nombre, raza, especie, id_cliente) values ('William', 'somali', 'GATO', 93);
insert into mascota (nombre, raza, especie, id_cliente) values ('Roderick', 'siames', 'GATO', 42);
insert into mascota (nombre, raza, especie, id_cliente) values ('Esther', 'Angora', 'GATO', 44);
insert into mascota (nombre, raza, especie, id_cliente) values ('Prudy', 'Abisinio', 'GATO', 21);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tyne', 'Bengala', 'GATO', 4);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sam', 'Angora', 'GATO', 38);
insert into mascota (nombre, raza, especie, id_cliente) values ('Avis', 'siames', 'GATO', 25);
insert into mascota (nombre, raza, especie, id_cliente) values ('Arlyn', 'somali', 'GATO', 62);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nat', 'siames', 'GATO', 26);
insert into mascota (nombre, raza, especie, id_cliente) values ('Leigh', 'Abisinio', 'GATO', 70);
insert into mascota (nombre, raza, especie, id_cliente) values ('Aleksandr', 'Angora', 'GATO', 94);
insert into mascota (nombre, raza, especie, id_cliente) values ('Georgetta', 'Angora', 'GATO', 75);
insert into mascota (nombre, raza, especie, id_cliente) values ('Wang', 'Angora', 'GATO', 20);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dugald', 'siames', 'GATO', 38);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ami', 'somali', 'GATO', 82);
insert into mascota (nombre, raza, especie, id_cliente) values ('Roselia', 'Angora', 'GATO', 17);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gar', 'somali', 'GATO', 85);
insert into mascota (nombre, raza, especie, id_cliente) values ('Jeanna', 'Angora', 'GATO', 35);
insert into mascota (nombre, raza, especie, id_cliente) values ('Henka', 'Bengala', 'GATO', 65);
insert into mascota (nombre, raza, especie, id_cliente) values ('Loree', 'somali', 'GATO', 35);
insert into mascota (nombre, raza, especie, id_cliente) values ('Arley', 'Bengala', 'GATO', 84);
insert into mascota (nombre, raza, especie, id_cliente) values ('Hildagarde', 'esfinge', 'GATO', 6);
insert into mascota (nombre, raza, especie, id_cliente) values ('Myrtie', 'somali', 'GATO', 78);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nick', 'esfinge', 'GATO', 50);
insert into mascota (nombre, raza, especie, id_cliente) values ('Reinwald', 'Angora', 'GATO', 64);
insert into mascota (nombre, raza, especie, id_cliente) values ('Walker', 'esfinge', 'GATO', 12);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sergio', 'esfinge', 'GATO', 63);
insert into mascota (nombre, raza, especie, id_cliente) values ('Tony', 'siames', 'GATO', 41);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dacia', 'somali', 'GATO', 46);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bamby', 'somali', 'GATO', 92);
insert into mascota (nombre, raza, especie, id_cliente) values ('Craggy', 'Abisinio', 'GATO', 64);
insert into mascota (nombre, raza, especie, id_cliente) values ('Juliane', 'esfinge', 'GATO', 11);
insert into mascota (nombre, raza, especie, id_cliente) values ('Celinda', 'Abisinio', 'GATO', 65);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dallas', 'siames', 'GATO', 79);
insert into mascota (nombre, raza, especie, id_cliente) values ('Chaim', 'Abisinio', 'GATO', 71);
insert into mascota (nombre, raza, especie, id_cliente) values ('Douglas', 'siames', 'GATO', 9);
insert into mascota (nombre, raza, especie, id_cliente) values ('Kane', 'somali', 'GATO', 76);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lay', 'siames', 'GATO', 28);
insert into mascota (nombre, raza, especie, id_cliente) values ('Geneva', 'siames', 'GATO', 20);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lanni', 'siames', 'GATO', 56);
insert into mascota (nombre, raza, especie, id_cliente) values ('Juliette', 'siames', 'GATO', 99);
insert into mascota (nombre, raza, especie, id_cliente) values ('Janean', 'siames', 'GATO', 32);
insert into mascota (nombre, raza, especie, id_cliente) values ('Con', 'Abisinio', 'GATO', 50);
insert into mascota (nombre, raza, especie, id_cliente) values ('Dominique', 'somali', 'GATO', 50);
insert into mascota (nombre, raza, especie, id_cliente) values ('Gwynne', 'esfinge', 'GATO', 28);
insert into mascota (nombre, raza, especie, id_cliente) values ('Siouxie', 'Bengala', 'GATO', 40);
insert into mascota (nombre, raza, especie, id_cliente) values ('Kerwin', 'siames', 'GATO', 98);
insert into mascota (nombre, raza, especie, id_cliente) values ('Paco', 'somali', 'GATO', 9);
insert into mascota (nombre, raza, especie, id_cliente) values ('Nicholas', 'Abisinio', 'GATO', 49);
insert into mascota (nombre, raza, especie, id_cliente) values ('Debor', 'somali', 'GATO', 18);
insert into mascota (nombre, raza, especie, id_cliente) values ('Godfree', 'Bengala', 'GATO', 90);
insert into mascota (nombre, raza, especie, id_cliente) values ('Merry', 'Bengala', 'GATO', 5);
insert into mascota (nombre, raza, especie, id_cliente) values ('Lolita', 'somali', 'GATO', 64);
insert into mascota (nombre, raza, especie, id_cliente) values ('Thorsten', 'siames', 'GATO', 9);
insert into mascota (nombre, raza, especie, id_cliente) values ('Angelica', 'Angora', 'GATO', 88);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ollie', 'siames', 'GATO', 88);
insert into mascota (nombre, raza, especie, id_cliente) values ('Townsend', 'Bengala', 'GATO', 33);
insert into mascota (nombre, raza, especie, id_cliente) values ('Irina', 'siames', 'GATO', 34);
insert into mascota (nombre, raza, especie, id_cliente) values ('Willa', 'esfinge', 'GATO', 11);
insert into mascota (nombre, raza, especie, id_cliente) values ('Fernande', 'Angora', 'GATO', 15);
insert into mascota (nombre, raza, especie, id_cliente) values ('Aloisia', 'siames', 'GATO', 39);
insert into mascota (nombre, raza, especie, id_cliente) values ('Baxie', 'Abisinio', 'GATO', 79);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sallyanne', 'Bengala', 'GATO', 32);
insert into mascota (nombre, raza, especie, id_cliente) values ('Virgilio', 'Bengala', 'GATO', 83);
insert into mascota (nombre, raza, especie, id_cliente) values ('Chad', 'Abisinio', 'GATO', 20);
insert into mascota (nombre, raza, especie, id_cliente) values ('Adrian', 'esfinge', 'GATO', 2);
insert into mascota (nombre, raza, especie, id_cliente) values ('Godfree', 'somali', 'GATO', 18);
insert into mascota (nombre, raza, especie, id_cliente) values ('Raphaela', 'Abisinio', 'GATO', 22);
insert into mascota (nombre, raza, especie, id_cliente) values ('Marcile', 'somali', 'GATO', 20);
insert into mascota (nombre, raza, especie, id_cliente) values ('Carlene', 'Abisinio', 'GATO', 46);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ethelyn', 'somali', 'GATO', 16);
insert into mascota (nombre, raza, especie, id_cliente) values ('Sadella', 'somali', 'GATO', 88);
insert into mascota (nombre, raza, especie, id_cliente) values ('Daffy', 'somali', 'GATO', 34);
insert into mascota (nombre, raza, especie, id_cliente) values ('Guntar', 'esfinge', 'GATO', 58);
insert into mascota (nombre, raza, especie, id_cliente) values ('Zorine', 'somali', 'GATO', 33);
insert into mascota (nombre, raza, especie, id_cliente) values ('Hiram', 'esfinge', 'GATO', 82);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ruby', 'siames', 'GATO', 26);
insert into mascota (nombre, raza, especie, id_cliente) values ('Merilee', 'Abisinio', 'GATO', 90);
insert into mascota (nombre, raza, especie, id_cliente) values ('Abbe', 'esfinge', 'GATO', 100);
insert into mascota (nombre, raza, especie, id_cliente) values ('Clywd', 'Abisinio', 'GATO', 54);
insert into mascota (nombre, raza, especie, id_cliente) values ('Robenia', 'Angora', 'GATO', 24);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ebba', 'Angora', 'GATO', 34);
insert into mascota (nombre, raza, especie, id_cliente) values ('Ammamaria', 'Abisinio', 'GATO', 27);
insert into mascota (nombre, raza, especie, id_cliente) values ('Leanna', 'Abisinio', 'GATO', 54);
insert into mascota (nombre, raza, especie, id_cliente) values ('Pietro', 'esfinge', 'GATO', 89);
insert into mascota (nombre, raza, especie, id_cliente) values ('Karisa', 'Bengala', 'GATO', 40);
insert into mascota (nombre, raza, especie, id_cliente) values ('Eddy', 'siames', 'GATO', 21);
insert into mascota (nombre, raza, especie, id_cliente) values ('Bengt', 'esfinge', 'GATO', 23);
insert into mascota (nombre, raza, especie, id_cliente) values ('Kendell', 'Bengala', 'GATO', 15);
insert into mascota (nombre, raza, especie, id_cliente) values ('Shelba', 'Abisinio', 'GATO', 79);
insert into tipo_cliente (id, descripcion) values (1, 'cliente');
insert into tipo_cliente (id, descripcion) values (2, 'invitado');
insert into tipo_servicio (id, descripcion, costo) values (1, 'medicado', 50000);
insert into tipo_servicio (id, descripcion, costo) values (2, 'anti pulgas', 45000);
insert into tipo_servicio (id, descripcion, costo) values (3, 'basico', 40000);